tinyMCE.addI18n('en.table_dlg',{
general_tab:"Общи",
advanced_tab:"Разширени",
general_props:"Общи свойства",
advanced_props:"Разширени свойства",
rowtype:"Ред в таблица",
title:"Вмъкни/Промени таблица",
width:"Широчина",
height:"Височина",
cols:"Колони",
rows:"Редове",
cellspacing:"Разстояние между клетки",
cellpadding:"Отстъп в клетките",
border:"Контур",
align:"Подравняване",
align_default:"Стандартно",
align_left:"Ляво",
align_right:"Дясно",
align_middle:"Централно",
row_title:"Свойства на ред",
cell_title:"Свойства на клетка",
cell_type:"Вид клетка",
valign:"Вертикално подравняване",
align_top:"Горе",
align_bottom:"Долу",
bordercolor:"Цвят на контура",
bgcolor:"Цвят на фона",
merge_cells_title:"Сливане на клетки",
id:"Id",
style:"Стил",
langdir:"Подреждане на текста",
langcode:"Код на текста",
mime:"Цел тип MIME",
ltr:"Отляво надясно",
rtl:"Отдясно наляво",
bgimage:"Изображение за фон",
summary:"Резюме",
td:"Данни",
th:"Шапка",
cell_cell:"Промени тази клетка",
cell_row:"Промени всички клетки в реда",
cell_all:"Промени всички клетки в таблицата",
row_row:"Обнови този ред",
row_odd:"Обнови нечетните редове в таблицата",
row_even:"Обнови четните редове в таблицата",
row_all:"Обнови всички редове в таблицата",
thead:"Шапка",
tbody:"Тяло",
tfoot:"Стъпало",
scope:"Обсег",
rowgroup:"Група редове",
colgroup:"Група колони",
col_limit:"Надхвърлен максимален брой колони от {$cols}.",
row_limit:"Надхвърлен максимален брой редове от {$rows}.",
cell_limit:"Надхвърлен максимален брой клетки от {$cells}.",
missing_scope:"Сигурни ли сте, че искате да продължите, без да отбележите дължина на head клетката. В такъв случай ще бъде трудно на някои хора с увреждания да разбера съдържанието или данните, представени в таблицата.",
caption:"Заглавие на таблицата",
frame:"Рамка",
frame_none:"нищо",
frame_groups:"групи",
frame_rows:"редове",
frame_cols:"колони",
frame_all:"всичко",
rules:"Линии",
rules_void:"празен",
rules_above:"над",
rules_below:"под",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"кутийка",
rules_border:"контур"
});