tinyMCE.addI18n('en.advanced',{
style_select:"Стилове",
font_size:"Размер на шрифт",
fontdefault:"Тип шрифт",
block:"Формат",
paragraph:"Параграф",
div:"Div",
address:"Адрес",
pre:"Преформатиран",
h1:"Заглавие 1",
h2:"Заглавие 2",
h3:"Заглавие 3",
h4:"Заглавие 4",
h5:"Заглавие 5",
h6:"Заглавие 6",
blockquote:"Цитат",
code:"Код",
samp:"Код мостра",
dt:"Оределящ термин ",
dd:"Определящо описание",
bold_desc:"Удебелен (Ctrl+B)",
italic_desc:"Наклонен (Ctrl+I)",
underline_desc:"Подчертан (Ctrl+U)",
striketrough_desc:"Зачертан",
justifyleft_desc:"Ляво",
justifycenter_desc:"Централно",
justifyright_desc:"Дясно",
justifyfull_desc:"Двустранно",
bullist_desc:"Булет списък",
numlist_desc:"Номериран списък",
outdent_desc:"Отстъп",
indent_desc:"Врязване",
undo_desc:"Върни (Ctrl+Z)",
redo_desc:"Напред (Ctrl+Y)",
link_desc:"Вмъкни/промени линк",
unlink_desc:"Махни линк",
image_desc:"Вмъкни/промени изображение",
cleanup_desc:"Почисти кода",
code_desc:"Промени HTML сорс",
sub_desc:"Долен индекс",
sup_desc:"Горен индекс",
hr_desc:"Вмъкни хоризонтална линия",
removeformat_desc:"Изтрий форматирането",
custom1_desc:"Вашето обяснение тук",
forecolor_desc:"Избери цвят на текста",
backcolor_desc:"Избери маркер за текста",
charmap_desc:"Избери символ",
visualaid_desc:"Премини към помощни линии/невидими елементи",
anchor_desc:"Вмъкни/промени котва",
cut_desc:"Изрежи",
copy_desc:"Копирай",
paste_desc:"Вмъкни",
image_props_desc:"Свойства на изображение",
newdocument_desc:"Нов документ",
help_desc:"Помощ",
blockquote_desc:"Цитат",
clipboard_msg:"Копирай/Изрежи/Вмъкни не са валидни за Mozilla и Firefox.\nИскате ли допълнителна информация по този проблем?",
path:"Път",
newdocument:"Сигурни ли сте, че искате да започнете нов документ?",
toolbar_focus:"Отиди към инструменти - Alt+Q, отиди към редактор - Alt-Z, Отиди към местоположение на елемент - Alt-X",
more_colors:"Повече цветове"
});