tinyMCE.addI18n('en.advanced_dlg',{
about_title:"Относно TinyMCE",
about_general:"Относно",
about_help:"Помощ",
about_license:"Лиценз",
about_plugins:"Добавки",
about_plugin:"Добавка",
about_author:"Автор",
about_version:"Версия",
about_loaded:"Заредени добавки",
anchor_title:"Вмъкни/промени котва",
anchor_name:"Име на котва",
code_title:"HTML редактор на сорс код",
code_wordwrap:"Ограничи текст",
colorpicker_title:"Избери цвят",
colorpicker_picker_tab:"Пипета",
colorpicker_picker_title:"Избор на цвят",
colorpicker_palette_tab:"Палета",
colorpicker_palette_title:"Цветове",
colorpicker_named_tab:"Именувани",
colorpicker_named_title:"Именувани цветове",
colorpicker_color:"Цвят:",
colorpicker_name:"Име:",
charmap_title:"Избери символ",
image_title:"Вмъкни/промени изображение",
image_src:"Изображение URL",
image_alt:"Описание",
image_list:"Списък изображения",
image_border:"Рамка",
image_dimensions:"Измерения",
image_vspace:"Вертикално пространство",
image_hspace:"Хоризонтално пространство",
image_align:"Подравняване",
image_align_baseline:"Основа",
image_align_top:"Връх",
image_align_middle:"Среда",
image_align_bottom:"Дъно",
image_align_texttop:"Текст горе",
image_align_textbottom:"Текст долу",
image_align_left:"Ляво",
image_align_right:"Дясно",
link_title:"Вмъкни/промени линк",
link_url:"Линк URL",
link_target:"Цел",
link_target_same:"Отвори линка в същия прозорец",
link_target_blank:"Отвори линка в нов прозорец",
link_titlefield:"Заглавие",
link_is_email:"Адресът, който сте въвели, прилича на адрес на имейл поща; желаете ли да добавите задължителната представка mailto: ?",
link_is_external:"Адресът, който сте въвели, е външен лик; желаете ли да добавите задължителната представка http:// ?",
link_list:"Списък линкове"
});