tinyMCE.addI18n('en.xhtmlxtras_dlg',{
attribute_label_title:"Заглавие",
attribute_label_id:"ID",
attribute_label_class:"Клас",
attribute_label_style:"Стил",
attribute_label_cite:"Цитат",
attribute_label_datetime:"Дата/Час",
attribute_label_langdir:"Посока на текст",
attribute_option_ltr:"Отляво надясно",
attribute_option_rtl:"Отдясно наляво",
attribute_label_langcode:"Език",
attribute_label_tabindex:"Индекс таб",
attribute_label_accesskey:"Ключ за достъп",
attribute_events_tab:"Събития",
attribute_attrib_tab:"Атрибути",
general_tab:"Общи",
attrib_tab:"Атрибути",
events_tab:"Събития",
fieldset_general_tab:"Общи настройки",
fieldset_attrib_tab:"Атрибути на елементи",
fieldset_events_tab:"Събития на елементи",
title_ins_element:"Вмъкване на елемент",
title_del_element:"ИЗтриване на елемент",
title_acronym_element:"Акроним",
title_abbr_element:"Съкращение",
title_cite_element:"Цитат",
remove:"Изтрий",
insert_date:"Вмъкни актуална дата/час",
option_ltr:"Отляво надясно",
option_rtl:"Отдясно наляво",
attribs_title:"Вмъкни/Промени атрибути"
});