tinyMCE.addI18n('en.style_dlg',{
title:"Промени CSS стил",
apply:"Приложи",
text_tab:"Текст",
background_tab:"Фон",
block_tab:"Блок",
box_tab:"Кутийка",
border_tab:"Контур",
list_tab:"Списък",
positioning_tab:"Позициониране",
text_props:"Текст",
text_font:"Шрифт",
text_size:"Размер",
text_weight:"Дебелина",
text_style:"Стил",
text_variant:"Формат",
text_lineheight:"Височина на ред",
text_case:"Случай",
text_color:"Цвят",
text_decoration:"Украса",
text_overline:"над линия",
text_underline:"подчертано",
text_striketrough:"зачертано",
text_blink:"мигащо",
text_none:"никакво",
background_color:"Цвят на фон",
background_image:"Изображение за фон",
background_repeat:"Повторение",
background_attachment:"Прикачване",
background_hpos:"Хоризонтална позиция",
background_vpos:"Вертикална позиция",
block_wordspacing:"Разстояние между думите",
block_letterspacing:"Разстояние между буквите",
block_vertical_alignment:"Вертикално подравняване",
block_text_align:"Подравняване",
block_text_indent:"Отстъп",
block_whitespace:"Празно място",
block_display:"Покажи",
box_width:"Широчина",
box_height:"Височина",
box_float:"Позиция",
box_clear:"Заключване",
padding:"Падинг",
same:"Еднакво за всички",
top:"Връх",
right:"Дясно",
bottom:"Долу",
left:"Ляво",
margin:"Поле",
style:"Стил",
width:"Широчина",
height:"Височина",
color:"Цвят",
list_type:"Тип",
bullet_image:"Булет",
position:"Позиция",
positioning_type:"Тип",
visibility:"Видимост",
zindex:"Наслагване",
overflow:"Излизане извън очертанията",
placement:"Поставяне",
clip:"Клип"
});