tinyMCE.addI18n('en.advlink_dlg',{
title:"Вмъкни/промени линк",
url:"Линк URL",
target:"Цел",
titlefield:"Заглавие",
is_email:"Адресът, който сте въвели, прилича на имейл адрес; искате ли да добавите задължителната представка mailto: ?",
is_external:"Адресът, който сте въвели, прилича на външен линк; искате ли да добавите задължителната представка http:// ?",
list:"Списък линкове",
general_tab:"Общи",
popup_tab:"Popup",
events_tab:"Събития",
advanced_tab:"Разширени",
general_props:"Общи свойства",
popup_props:"Popup свойства",
event_props:"Събития",
advanced_props:"Разширени свойства",
popup_opts:"Опции",
anchor_names:"Котви",
target_same:"Отвори в този прозорец / рамка",
target_parent:"Отвори в под-прозорец / рамка",
target_top:"Отвори в основна рамка (заменя всички рамки)",
target_blank:"Отвори в нов прозорец",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Име на прозорец",
popup_return:"Вмъкни 'върни грешка'",
popup_scrollbars:"Покажи скрол",
popup_statusbar:"Покажи статус бар",
popup_toolbar:"Покажи лента с инструменти",
popup_menubar:"Покажи меню",
popup_location:"Покажи местоположение",
popup_resizable:"Оразмери прозореца",
popup_dependent:"Зависим (Mozilla/Firefox само)",
popup_size:"Размер",
popup_position:"Позиция (X/Y)",
id:"Id",
style:"Стил",
classes:"Класове",
target_name:"Име на цел",
langdir:"Посока на текста",
target_langcode:"Текст на целта",
langcode:"Код на текста",
encoding:"Кодиране на целта",
mime:"Цел тип MIME",
rel:"Отношение страница към цел",
rev:"Отношение цел към страница",
tabindex:"Индекс",
accesskey:"Ключ за достъп",
ltr:"Отляво надясно",
rtl:"Отдясно наляво",
link_list:"Списък линкове"
});